project:
  type: website
  output-dir: doc

website:
  title: "The IPBES Guide on the production of assessments"
  navbar:
    left:
      - about.qmd
      - text: How to Use this Guide
        file: howto_guide.qmd
      - text: Background
        file: Background.qmd
      - text: "Stage 1"
        file: Stage_1.qmd
      - text: "Stage 2"
        menu:
          - text: "Before Assessment Start"
            file: Stage_2.qmd
          - text: "Researcher During Assessment"
            file: Stage_2.qmd
          - text: "Reviewer"
            file: Stage_2.qmd
      - text: "Stage 3"
        file: Stage_3.qmd
      - text: "Stage 4"
        file: Stage_4.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
