project:
  type: website
  output-dir: doc

website:
  title: "The IPBES Guide on the production of assessments"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: TODOs
        file: todos.qmd
      - about.qmd
      - text: Introduction
        file: Introduction.qmd
      - text: "Stage 1"
        file: Stage_1.qmd
      - text: "Stage 2"
        file: Stage_2.qmd
      - text: "Stage 3"
        file: Stage_3.qmd
      - text: "Stage 4"
        file: Stage_4.qmd
      - text: "Complete"
        file: Complete.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
