---
title: "Stage 4: Use of the assessment findings"
format: html
---

2.4 Stage 4: Use of the assessment findings

2.4.1 Outreach and support for use

> The release of the assessment report, including the front matter
> (preface), the SPM, the chapters and the back matter (annexes), is
> supported by a communication strategy. The communication strategy will
> be developed by the assessment management committee and approved by
> the Bureau. The aim of the communication strategy is to ensure that
> the assessment results are appropriately communicated and that they
> reach the target audiences.
>
> The communication strategy may include the following steps:

- Selection and hiring of a media consultants to assist with the
  implementation of the strategy.

- Identification of the main target audiences related to the assessment.

- Finalization of the communication strategy for the assessment with the
  media consultant, taking into account the IPBES communication,
  outreach and stakeholder engagement strategy and the needs of the
  relevant target audiences and stakeholders.

- Communication ahead of the Plenary session where the SPM will be
  accepted.

- Preparation of press releases.

- Preparation of other media materials (including press kits, mini
  videos explaining the SPM content and PowerPoint presentations on the
  outcomes of the assessment).

<!-- -->

- Mobilization of all partners and stakeholders to help promote the
  assessment reports and expand their overall reach and impact.

- Webinar with key journalists ahead of the Plenary.

- Outreach with social media.

- Media training for IPBES authors, as well as selected MEP, Bureau and
  secretariat staff.

- Communication during the Plenary.

- Press conference to announce the approval of the SPM.

- Interviews with press, TV and radio in response to requests.

- Communication after the Plenary.

- Publication of printed versions of the SPM and technical reports.

- Additional press conferences as appropriate.

- Media monitoring and follow-up.

- Engagement over the course of the year with different audiences and
  stakeholders following the approval of the SPM, including conference
  and events.

> IPBES uses embargoed releases and interviews prior to the launch of
> the SPM as a means to ensure a disciplined approach to the
> dissemination of its key messages and findings. This approach is
> implemented after the approval of the SPMs by member States.
>
> The Platform's key strategic objectives at the launch of an
> assessment, which is a period of heightened activity, are first to
> maintain vigorous, accurate and sustained press coverage; second, to
> coordinate and control messaging that is kept strictly within the
> bounds set for the Platform's reports, namely that they should be
> policy relevant, not policy prescriptive; and third, to meet the
> requests made by end users -- policymakers and scientific and
> technical experts in government and the private sector in particular
> -- for the conduct of seminars, briefings and meetings.[^1]
>
> Communicating the results of the Platform's assessments will be a
> challenging task because of the range and complexity of scientific
> issues and the increasing need to reach audiences beyond scientists
> and governments. With the help of a communications consulting firm,
> clear messages can be crafted for different audiences. Furthermore,
> trained science writers can translate technical language into text
> suitable for mass communication or can design web pages that explain
> scientific concepts to audiences without misconstruing or distorting
> the evidence underpinning those concepts.[^2]
>
> The presentation of the findings of the assessment reports, in
> particular the launch of the Pollination Assessment, led to very
> intense press activity with articles appearing on all major newswires
> (Reuters, AFP, EFE, etc.), 1,200 online news articles in 25 languages
> across 80 countries, plus numerous articles in print newspapers (e.g.,
> NY times) and abundant radio coverage. "Jeopardy", a long-running US
> TV game show with an average daily audience of nine million, also
> included a question based on the IPBES report in its April 26, 2016
> broadcast (category: "Science Update"). A table summarizing all of
> these press articles is included on the IPBES website
> ([www.ipbes.net/article/ipbes-pollinationreport-media-coverage](http://www.ipbes.net/article/ipbes-pollinationreport-media-coverage)).[^3]
>
> **Other activities in addition to the communication strategy** can be
> undertaken to encourage the use of the key findings of the assessment.
> These include:

- Working with key partners on the use of findings, such as the parties
  and observers under relevant multilateral agreements;

- Making knowledge and data gaps identified within the assessments
  available to the scientific community and research funding agencies
  (through the use of the knowledge catalysis function of IPBES) in
  order to generate further research, monitoring and modelling;

- Working with countries, through capacity building activities, to
  implement mechanisms which will help to leverage further impacts of
  IPBES products, such as through national platforms and national
  assessments;

- Capturing information on policy support tools in IPBES assessments and
  including it in the IPBES Catalogue to allow users to search and
  access the tools; and

- Preparing a number of scientific publications on various aspects of
  the reports, undertaken by experts in the published assessments, which
  will be listed on the IPBES website.

[^1]: IPBES-3/4 : Communication, stakeholder engagement and strategic
    partnerships.
    https://www.ipbes.net/document-library-catalogue/decision-ipbes-34

[^2]: IPBES/3/18: Meeting report.
    https://www.ipbes.net/document-library-catalogue/ipbes318

[^3]: See the Bureau report here:
    https://www.ipbes.net/sites/default/files/downloads/pdf/IPBES-Bureau_7_10%20COM.pdf
