name: Render and Publish Quarto Website

on:
  push:
    branches: [main] # or your default working branch
  workflow_dispatch: # allow manual trigger

jobs:
  render-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Render site
        run: quarto render

      - name: Publish to web branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_branch: web
          publish_dir: ./doc # or whatever your output-dir is
