# Tests:
# 1. render using quarto

on:
  pull_request:
  push:
    branches-ignore:
      - main

name: Quarto Publish

jobs:
  build-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show commit info
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site (Test only)
        run: quarto render
